(import (rnrs base)
        (srfi :64)
        (srfi :41)
        (prolog)
        (only (chezscheme) include interaction-environment))
(current-lisp-environment (interaction-environment))
(include "test/test.scm")
