# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@jcubic/lily-0.1.0" = {
      name = "_at_jcubic_slash_lily";
      packageName = "@jcubic/lily";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jcubic/lily/-/lily-0.1.0.tgz";
        sha512 = "kIsp4dmIUHn3YHIqFhEylY+mgI988KcYI8f19og7LqmLzkouPZNBip/oL8iemElie0gqx5CeQ5HxZv/SuNkOaA==";
      };
    };
    "@jcubic/lily-0.4.0" = {
      name = "_at_jcubic_slash_lily";
      packageName = "@jcubic/lily";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jcubic/lily/-/lily-0.4.0.tgz";
        sha512 = "Ls2myk57bfXPS9XdNZ7Kbbbx4veQgZG64UpFYLDuPhe/NSqeHW88iz09YZdbpYOSNNQiQKN8D5HN+nLI1ot7Gg==";
      };
    };
    "bn.js-5.2.2" = {
      name = "bn.js";
      packageName = "bn.js";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bn.js/-/bn.js-5.2.2.tgz";
        sha512 = "v2YAxEmKaBLahNwE1mjp4WON6huMNeuDvagFZW+ASCuA/ku0bXR9hSMw0XpiqMoA3+rmnyck/tPRSFQkoC9Cuw==";
      };
    };
    "cbor-extract-2.2.0" = {
      name = "cbor-extract";
      packageName = "cbor-extract";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cbor-extract/-/cbor-extract-2.2.0.tgz";
        sha512 = "Ig1zM66BjLfTXpNgKpvBePq271BPOvu8MR0Jl080yG7Jsl+wAZunfrwiwA+9ruzm/WEdIV5QF/bjDZTqyAIVHA==";
      };
    };
    "cbor-x-1.6.0" = {
      name = "cbor-x";
      packageName = "cbor-x";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cbor-x/-/cbor-x-1.6.0.tgz";
        sha512 = "0kareyRwHSkL6ws5VXHEf8uY1liitysCVJjlmhaLG+IXLqhSaOO+t63coaso7yjwEzWZzLy8fJo06gZDVQM9Qg==";
      };
    };
    "compare-versions-6.1.1" = {
      name = "compare-versions";
      packageName = "compare-versions";
      version = "6.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/compare-versions/-/compare-versions-6.1.1.tgz";
        sha512 = "4hm4VPpIecmlg59CHXnRDnqGplJFrbLG4aFEl5vl6cK1u76ws3LLvX7ikFnTDl5vo39sjWD6AaDPYodJp/NNHg==";
      };
    };
    "detect-libc-2.0.4" = {
      name = "detect-libc";
      packageName = "detect-libc";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/detect-libc/-/detect-libc-2.0.4.tgz";
        sha512 = "3UDv+G9CsCKO1WKMGw9fwq/SWJYbI0c5Y7LU1AXYoDdbhE2AHQ6N6Nb34sG8Fj7T5APy8qXDCKuuIHd1BR0tVA==";
      };
    };
    "has-flag-4.0.0" = {
      name = "has-flag";
      packageName = "has-flag";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-flag/-/has-flag-4.0.0.tgz";
        sha512 = "EykJT/Q1KjTWctppgIAgfSO0tKVuZUjhgMr17kqTumMl6Afv3EISleU7qZUzoXDFTAHTDC4NOoG/ZxU3EvlMPQ==";
      };
    };
    "lzjb-pack-0.2.0" = {
      name = "lzjb-pack";
      packageName = "lzjb-pack";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lzjb-pack/-/lzjb-pack-0.2.0.tgz";
        sha512 = "kq31VT9O9XoSR5kdXYglGDeDKgAfmu39MWrc7TzYVJBRT6UMc5PSYhkZHdqKiBFKVk9e5DWNyBF3Yji1GifD+Q==";
      };
    };
    "node-gyp-build-optional-packages-5.1.1" = {
      name = "node-gyp-build-optional-packages";
      packageName = "node-gyp-build-optional-packages";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build-optional-packages/-/node-gyp-build-optional-packages-5.1.1.tgz";
        sha512 = "+P72GAjVAbTxjjwUmwjVrqrdZROD4nf8KgpBoDxqXXTiYZZt/ud60dE5yvCSr9lRO8e8yv6kgJIC0K0PfZFVQw==";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha512 = "WfnNWLS3vr8omCm8nKYKaRbapuy6pEbx1O0B+eP5sUf/a++sT9/h8PflqBoHsY9N+YdzUT12T8snXigq13QpJg==";
      };
    };
    "prism-cli-0.5.3" = {
      name = "prism-cli";
      packageName = "prism-cli";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/prism-cli/-/prism-cli-0.5.3.tgz";
        sha512 = "8tuw/MmG/U3d74j5JTWvTI6quEV4G4a5vsso0LDaYBFEbPd1yN3V/VuOYk47IKS2Iuj8E7j1WPQAFCUEdULo3w==";
      };
    };
    "prismjs-1.30.0" = {
      name = "prismjs";
      packageName = "prismjs";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prismjs/-/prismjs-1.30.0.tgz";
        sha512 = "DEvV2ZF2r2/63V+tK8hQvrR2ZGn10srHbXviTlcv7Kpzw8jWiNTqbVgjO3IY8RxrrOUF8VPMQQFysYYYv0YZxw==";
      };
    };
    "supports-color-7.2.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "7.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-7.2.0.tgz";
        sha512 = "qpCAvRl9stuOHveKsn7HncJRvv501qIacKzQlO/+Lwxc9+0q2wLyv4Dfvt80/DPn2pqOBsJdDiogXGR9+OvwRw==";
      };
    };
    "unfetch-5.0.0" = {
      name = "unfetch";
      packageName = "unfetch";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unfetch/-/unfetch-5.0.0.tgz";
        sha512 = "3xM2c89siXg0nHvlmYsQ2zkLASvVMBisZm5lF3gFDqfF2xonNStDJyMpvaOBe0a1Edxmqrf2E0HBdmy9QyZaeg==";
      };
    };
  };
in
{
  biwascheme = nodeEnv.buildNodePackage {
    name = "biwascheme";
    packageName = "biwascheme";
    version = "0.8.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/biwascheme/-/biwascheme-0.8.0.tgz";
      sha512 = "zuoqaX8zPsXJDHZZC4cSYbP3mAvuVKrIUCR1pChjfi/9Zp5WTYhO3qjv4zOazu5Zfdd/pEN4GcSMCM6rYXHHiw==";
    };
    dependencies = [
      sources."optparse-1.0.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A practical Scheme interpreter written in JavaScript";
      homepage = "https://www.biwascheme.org/";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  lips = nodeEnv.buildNodePackage {
    name = "lips";
    packageName = "lips";
    version = "1.0.0-beta.20";
    src = fetchurl {
      url = "https://registry.npmjs.org/lips/-/lips-1.0.0-beta.20.tgz";
      sha512 = "aC9x+ZR9YZGVQ41r4ge6/NkwBrPkHHommifoVAJm82HHLxjaQPE/+B9EZQKlMU07eRLhXpmUlSncfvV+riHEeQ==";
    };
    dependencies = [
      sources."@jcubic/lily-0.4.0"
      sources."bn.js-5.2.2"
      sources."cbor-extract-2.2.0"
      sources."cbor-x-1.6.0"
      sources."compare-versions-6.1.1"
      sources."detect-libc-2.0.4"
      sources."has-flag-4.0.0"
      sources."lzjb-pack-0.2.0"
      sources."node-gyp-build-optional-packages-5.1.1"
      (sources."prism-cli-0.5.3" // {
        dependencies = [
          sources."@jcubic/lily-0.1.0"
        ];
      })
      sources."prismjs-1.30.0"
      sources."supports-color-7.2.0"
      sources."unfetch-5.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Simple Scheme Like Lisp in JavaScript";
      homepage = "https://github.com/jcubic/lips#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
