name: test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
        lisp: [gauche, guile, chicken, chibi, sagittarius, racket, gambit, chez, sbcl, ecl, clisp, abcl, ccl, mkcl, cmucl_binary, clasp-common-lisp]
        exclude:
          - os: macos-15
            lisp: ccl
          - os: macos-15
            lisp: mkcl
          - os: macos-15
            lisp: clasp-common-lisp
          - os: macos-15
            lisp: cmucl_binary
          - os: ubuntu-24.04-arm
            lisp: ccl
          - os: ubuntu-24.04-arm
            lisp: mkcl
          - os: ubuntu-24.04-arm
            lisp: clasp-common-lisp
          - os: ubuntu-24.04-arm
            lisp: cmucl_binary

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: extra-experimental-features = nix-command flakes

      - run: nix run .#test-${{ matrix.lisp }}
