name: scheme-ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, macos-latest, macos-14]
        runner: [ubuntu-latest, ubuntu-22.04-arm, macos-latest, macos-14]
        impl: [gauche, guile, chicken, chibi, sagittarius, gambit]

    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v31
        with:
          nix_conf: extra-experimental-features = nix-command flakes
          daemon: ${{ startsWith(matrix.os, 'macos-') }}

      - run: nix develop -c make IMPLS=${{ matrix.impl }}
        shell: bash
