name: scheme-ci

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, macos-latest, macos-14]
        impl: [gauche, guile, chicken, chibi, sagittarius, gambit, racket]
        exclude:
          - os: macos-latest
            impl: racket
          - os: macos-14
            impl: racket

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: extra-experimental-features = nix-command flakes

      - run: nix develop -c make ${{ matrix.impl }}
